/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    01: typeof import('./src/components/tab-bar/tab-bar 01.vue')['default']
    Loading: typeof import('./src/components/loading/loading.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/tab-bar.vue')['default']
    'TabBar 01': typeof import('./src/components/tab-bar/tab-bar 01.vue')['default']
    TabControl: typeof import('./src/components/tab-control/tab-control.vue')['default']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanRate: typeof import('vant/es')['Rate']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
